packages:
  - "api"
  - "web"
  - "contracts"

catalog:
  typescript: ^5.9.3

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false

verifyDepsBeforeRun: false